try {
    printName();
} catch (erros){
    console.log("Error", erros);
}
finally{
    console.log("Im Finally Block");
    
}
